accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.user_signup, name="signup"),
]

math_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_problems_list(request):
    return redirect("home")

urlpatterns = [
    path("", redirect_to_problems_list, name="home_page"),
    path("alwaysright/", include("problems.urls")),
    path("alwaysright/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

problems/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_page, name="home"),
    path("problems/<int:topic_id>", views.all_problems, name="problems_by_topic"),
    path("myproblems", views.my_problems, name="my_problems"),
    path("topics", views.all_topics, name="all_topics"),
    path("topics/add", views.add_a_topic, name="add_topics"),
    path("<int:id>", views.individual_math_problems, name="individual_problem"),
    path("ask", views.ask_a_problem, name="ask_a_problem"),
    path("<int:id>/solution", views.answer_a_problem, name="answer_a_problem"),
    path("<int:id>/solution/likes", views.like_solution, name = "like_solution"),
    path("<int:id>/solution/dislikes", views.dislike_solution, name = "dislike_solution"),
]

problems/models.py
from django.db import models
from django.conf import settings

class Topic(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True)

    def __str__(self):
        return self.name

class MathProblems(models.Model):
    question = models.TextField(null=True)
    questions_created_on = models.TimeField(auto_now_add=True)
    question_creater = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="questions",
        on_delete=models.CASCADE,
    )
    topic = models.ForeignKey(
        Topic,
        related_name="problems",
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ["topic"]

    def __str__(self):
        return self.question

class Solution(models.Model):
    solution = models.TextField(null=True)
    solutions_created_on = models.TimeField(auto_now=True)
    solution_creater = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="solutions",
        on_delete=models.CASCADE,
    )
    question = models.ForeignKey(
        MathProblems,
        related_name="solutions",
        on_delete=models.CASCADE,
        null=True,
    )
    likes = models.PositiveIntegerField(default = 0, null = True, blank = True)
    dislikes = models.PositiveIntegerField(default = 0, null = True, blank = True)

    class Meta:
        ordering = ["solutions_created_on"]

problems/forms.py
from problems.models import MathProblems, Topic, Solution
from django.forms import ModelForm

class MathQuestionAskForm(ModelForm):
    class Meta:
        model = MathProblems
        fields=["topic", "question", "question_creater"]


class MathQuestionAnswerForm(ModelForm):
    class Meta:
        model = Solution
        fields=["question", "solution", "solution_creater"]


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields=["name", "description"]

problems/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from problems.models import MathProblems, Solution, Topic
from problems.forms import MathQuestionAskForm, MathQuestionAnswerForm, TopicForm

def home_page(request):
    return render(request, "problems/home.html")

def all_topics(request):
    all_topics = Topic.objects.all()
    images = ['https://www.psychologicalscience.org/redesign/wp-content/uploads/2014/08/PAFF_082917_mathequations-609x419.jpg',
                   'https://media.istockphoto.com/id/1219382595/vector/math-equations-written-on-a-blackboard.jpg?s=612x612&w=0&k=20&c=ShVWsMm2SNCNcIjuWGtpft0kYh5iokCzu0aHPC2fV4A=',
                   'https://i.pinimg.com/originals/1d/13/ea/1d13ead1c85dc568429e9672b48875e2.jpg',
                   ]
    context={
        "all_topics": all_topics,
        "images": images,
    }
    return render(request, "problems/topic_list.html", context)


def all_problems(request, topic_id=None):
    topics = Topic.objects.all().prefetch_related('problems')
    if topic_id:
        problems = MathProblems.objects.filter(topic_id=topic_id)
    else:
        problems = MathProblems.objects.all()
    context = {
        "topics": topics,
        "problems": problems,
    }
    return render(request, "problems/question_list.html", context)


@login_required
def my_problems(request):
    my_problems = MathProblems.objects.filter(question_creater=request.user)
    context={
        "my_problems": my_problems,
    }
    return render(request, "problems/my_question.html", context)

@login_required
def add_a_topic(request):
    if request.method == "POST":
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("all_topics")
    else:
        form = TopicForm
        context = {
            "form": form,
        }
        return render(request, "problems/add_topic.html", context)

@login_required
def ask_a_problem(request):
    topics = Topic.objects.all()
    users = User.objects.all()

    if request.method == "POST":
        form = MathQuestionAskForm(request.POST)
        if form.is_valid():
            problem = form.save(False)
            problem.question_creater = request.user
            form.save()
            return redirect("my_problems")
    else:
        form = MathQuestionAskForm
        context = {
            "form": form,
            "topics": topics,
            "users": users,
        }
        return render(request, "problems/ask_question.html", context)

@login_required
def individual_math_problems(request, id):
    problems = get_object_or_404(MathProblems, id=id)
    context={
        "math_problems": problems,
    }
    return render(request, "problems/question.html", context)

@login_required
def answer_a_problem(request, id):
    question = get_object_or_404(MathProblems, id=id)
    users = User.objects.all()

    if request.method == "POST":
        form = MathQuestionAnswerForm(request.POST)
        if form.is_valid():
            solution = form.save(False)
            solution.solution_creater = request.user
            solution.math_problem = question
            form.save()
            return redirect("individual_problem", id=id)
    else:
        form = MathQuestionAnswerForm
    context = {
        "form": form,
        "question": question,
        "users": users,
    }
    return render(request, "problems/answer_question.html", context)

@login_required
def like_solution(request, id):
    solution = get_object_or_404(Solution, id=id)
    solution.likes += 1
    solution.save()
    return redirect("individual_problem", id=solution.question.id)

@login_required
def dislike_solution(request, id):
    solution = get_object_or_404(Solution, id=id)
    solution.dislikes += 1
    solution.save()
    return redirect("individual_problem", id=solution.question.id)

problems/templates/problems/add_topic.html
{% extends 'base.html' %}

{% block title %}
    Math Problem Solver
{% endblock title %}

{% block content %}
<main class="form-page">
    <form method="post">
        {% csrf_token %}
        <h1 class="form-title">Add Topics</h1>
        <p>
            <label class="label-name" for="id_name">Name</label>
            <br>
            <input class="input-name" type="text" name="name" maxlength="50" required id="id_name" placeholder="Topic Name">
        </p>
        <p>
            <label class="label-name" for="id_description">Description</label>
            <br>
            <textarea class="input-description" name="description" clos="40" rows="10" required id="id_description"></textarea>
        </p>
        <button class="form-button">ADD</button>
    </form>
</main>
{% endblock content %}

problems/templates/problems/answer_question.html
{% extends 'base.html' %}
{% block title %}
    Math Problem Solver
{% endblock title %}
{% block content %}
<main class="form-page">
    <form method="post">
        {% csrf_token %}
        <h1 class="form-title">Answer a Question</h1>
        <p>
            <h1 class="label-question">{{ question.question }}</h1>
        </p>
        <p>
            <label class="label-name" for="id_solution">Solution</label>
            <br>
            <textarea class="input-solution" name="solution" cols="40" rows="10" required id="id_solution"></textarea>
        </p>
        <p>
            <label class="label-name" for="id_solution_creater">Solution creater: </label>
            <select class="option" name="solution_creater" required id="id_solution_creater">
                <option value="user-selection">Select a user</option>
                {% for user in users %}
                    <option vaule="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </p>
        <button class="form-button">ANSWER</button>
    </form>
</main>
{% endblock content %}

problems/templates/problems/ask_question.html
{% extends 'base.html' %}

{% block title %}
    Math Problem Solver
{% endblock title %}

{% block content %}
<main class="form-page">
    <form method="post">
        {% csrf_token %}
        <h1 class="form-title">Ask a Question</h1>
        <p>
            <label class="label-name" for="id_topic">Topic: </label>
            <select class="option" name="topic" required id="id_topic">
                <option value="topic-selection">Select a topic</option>
                {% for topic in topics %}
                    <option value="{{ topic.id }}">{{ topic.name }}</option>
                {% endfor %}
            </select>
        </p>
        <p>
            <label class="label-name" for="id_question">Question</label>
            <br>
            <textarea class="input-question" name="question" cols="40" row="10" required id="id_question"></textarea>
        </p>
        <p>
            <label class="label-name" for="id_question_creater">Questions Creater: </label>
            <select class="option user-option" name="question_creater" required id="id_question_creater">
                <option value="user-selection">Select a user</option>
                {% for user in users %}
                    <option vaule="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </p>
        <button class="form-button">ADD</button>
    </form>
</main>
{% endblock content %}

problems/templates/problems/my_question.html
{% extends 'base.html' %}

{% block title %}
    Question List
{% endblock title %}

{% block content %}

<main>
    <div class="grid-container">

        {% for problem in my_problems %}
        <div class="grid-item">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="question-card-title">{{ problem.topic }}</h5>
                    <p class="question-card-text">{{ problem.question }}</p>
                    <a href="{% url 'individual_problem' problem.id %}" class="button-look question-button">Check Question</a>
                    <a href="" class="button-look delete-button">Delete Question</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>

</main>
{% endblock content %}

problems/templates/problems/question.html
{% extends 'base.html' %}

{% block title %}
    Math Problems {{ math_problems.id }}
{% endblock title %}

{% block content %}
<main>
    <div class="problem-page">
        <div class="problem">
            <h1 class="problem-topic">{{ math_problems.topic }}</h1>
            <p class="problem-question-info">{{ math_problems.question }}</p>
        </div>

        <div>
        {% for solution in math_problems.solutions.all %}
        <button type="button" class="collapsible">Open Solution</button>
        <div class="solution">
            <p class="solution-text">{{ solution.solution }}</p>
            <p class="solution-creater">Created By: {{ solution.solution_creater }}</p>
            <p class="solution-time">Created On: {{ solution.solutions_created_on }}</p>
            <div class="likes-dislikes">
              <form method="post" action="{% url 'like_solution' solution.id %}">
                {% csrf_token %}
                <button type="submit" class="like-button">
                  <i class="fa fa-thumbs-up"></i>{{ solution.likes }}
                </button>
              </form>
              <form method="post" action="{% url 'dislike_solution' solution.id %}">
                {% csrf_token %}
                <button type="submit" class="dislike-button">
                  <i class="fa fa-thumbs-down"></i>{{ solution.dislikes }}
                </button>
              </form>
            </div>
        </div>
        {% endfor %}
        </div>

        <div class="solution-button-container">
            <a class="button-look solution-page-button" href="{% url 'problems_by_topic' math_problems.topic.id %}">Back to Questions</a>
            <a class="button-look solution-page-button" href="{% url 'answer_a_problem' math_problems.id %}">Add Solution</a>
        </div>

    </div>

    <script>
        var coll = document.getElementsByClassName("collapsible");
        var i;

        for (i = 0; i < coll.length; i++) {
          coll[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
              content.style.display = "none";
            } else {
              content.style.display = "block";
            }
          });
        }
    </script>

</main>

{% endblock content %}

problems/templates/problems/question_list.html
{% extends 'base.html' %}

{% block title %}
    Question List
{% endblock title %}

{% block content %}

<main>
    <div class="grid-container">
            {% if problems %}
                {% for problem in problems %}
                <div class="grid-item">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title question-card-title">{{ problem.topic }}</h5>
                            <p class="card-text question-card-text">{{ problem.question }}</p>
                            <p class="card-text">Created by: {{ problem.question_creater }}</p>
                            <a href="{% url 'individual_problem' problem.id %}" class="question-button button-look topic-question-button">Check the Question</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <p>No questions found.</p>
            {% endif %}
    </div>

    <div class="question-list-button-container">
    <a class="button-look question-list-button" href="{% url 'all_topics' %}">Back to Topics</a>
    <a class="button-look question-list-button" href="{% url 'ask_a_problem' %}">Ask Question</a>
    </div>

</main>
{% endblock content %}

problems/templates/problems/topic_list.html
{% extends 'base.html' %}

{% block title %}
    Question List
{% endblock title %}

{% block content %}
<main>
    <div class="grid-container">
        {% for topic in all_topics %}
        <div class="grid-item">
            <div class="flip-card">
                <div class="flip-card-inner">
                  <div class="flip-card-front">
                    <img src="{{ images|random }}" alt="Avatar" style="width:300px;height:200px;">
                    <h5 class="question-card-title">{{ topic.name }}</h5>
                  </div>
                  <div class="flip-card-back">
                    <h5 class="question-card-title">{{ topic.name }}</h5>
                    <p class="topic-description">{{ topic.description }}</p>
                    <a href="{% url 'problems_by_topic' topic.id %}" class="button-look topic-button">Check the Questions</a>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock content %}