accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.user_signup, name="signup"),
]

math_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_problems_list(request):
    return redirect("home")

urlpatterns = [
    path("", redirect_to_problems_list, name="home_page"),
    path("alwaysright/", include("problems.urls")),
    path("alwaysright/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms


class LogInForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from accounts.forms import LogInForm, SignUpForm


def user_login(request):
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(
                request,
                username=username,
                password=password,
            )
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = LogInForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("home")


def user_signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                )
                login(request, user)
                return redirect("home")
            else:
                form.add_error("password", "the passwords do not match")
    else:
        form = SignUpForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>
    <main>
        <div class="form-img"></div>
        <div class="wrapper">
            <div class="form-box">
                <form method="post">
                    {% csrf_token %}
                        {% comment %} <div class="error">
                            {{ form.error }}
                        </div> {% endcomment %}
                    <div class="login-title">
                        <h1>Always Right</h1>
                        <h1>Login</h1>
                    </div>
                    <div class="inputbox">
                        <label for="#">{{ form.username.label }}</label>
                        {{ form.username }}
                    </div>
                    <div class="inputbox">
                        <label for="#">{{ form.password.label }}</label>
                        {{ form.password }}
                    </div>
                    <div class="checkboxes">
                        <label><input type="checkbox" name="remeber-me">Remember me</label>
                        <a href=""> Forgot password?</a>
                    </div>
                    <button class="form-button">Login</button>
                    <div class="login-register">
                        <a href="{% url 'signup' %}" class="register-link">Don't have an account?</a>
                    </div>
                    <div class="home-link">
                        <a href="{% url 'home' %}">Go to the home page</a>
                    </div>
                </form>
            </div>
        </div>
    </main>
</body>
</html>

accounts/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>
    <main>
        <div class="form-img"></div>
        <div class="wrapper">
            <div class="form-box">
                <form method="post">
                    {% csrf_token %}
                    {% comment %} {{ form.as_p }} {% endcomment %}
                    <div class="login-title">
                        <h1>Always Right</h1>
                        <h1>Signup</h1>
                    </div>
                    <div class="inputbox">
                        <p>
                            <label for="id_username">Username</label>
                            <input type="text" name="username" maxlength="150" required id="id_username">
                        </p>
                    </div>
                    <div class="inputbox">
                        <p>
                            <label for="id_password">Password</label>
                            <input type="password" name="password" maxlength="150" required id="id_password">
                        </p>
                    </div>
                    <div class="inputbox">
                        <p>
                            <label for="id_password_confirmation">Password confirmation</label>
                            <input type="password" name="password_confirmation" maxlength="150" required id="id_password_confirmation">
                        </p>
                    </div>
                    <button class="form-button">Signup</button>
                    <div class="login-register">
                        <a href="{% url 'login' %}" class="register-link">Already have an account? Sign In</a>
                    </div>
                    <div class="home-link">
                        <a href="{% url 'home' %}">Go to the home page</a>
                    </div>
                </form>
            </div>
        </div>
    </main>
</body>
</html>